# Generated by Django 4.1.2 on 2022-10-13 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0002_alter_user_username"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="avatar",
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="slogon",
            field=models.CharField(max_length=128, null=True),
        ),
    ]
