# Generated by Django 4.1.2 on 2022-10-21 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bill", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bill", name="bill_date", field=models.CharField(max_length=255),
        ),
    ]
