# Generated by Django 4.1.2 on 2022-10-21 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bill", "0002_alter_bill_bill_date"),
    ]

    operations = [
        migrations.DeleteModel(name="Bill",),
    ]
