# Generated by Django 4.1.2 on 2022-10-21 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bill", "0005_bills_delete_bill"),
    ]

    operations = [
        migrations.RenameModel(old_name="Bills", new_name="Bill",),
    ]
