# Generated by Django 4.1.2 on 2022-10-21 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bill", "0006_rename_bills_bill"),
    ]

    operations = [
        migrations.DeleteModel(name="Bill",),
    ]
