# Generated by Django 4.1.2 on 2022-10-22 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bill", "0008_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="bill",
            name="category_icon_name",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
