# Generated by Django 4.1.2 on 2022-10-25 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bill", "0011_alter_category_category_name"),
    ]

    operations = [
        migrations.RemoveField(model_name="bill", name="category_type",),
    ]
