# Generated by Django 4.1.2 on 2022-10-25 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bill", "0012_remove_bill_category_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="bill",
            name="category_type",
            field=models.CharField(default="Fixed", max_length=255),
            preserve_default=False,
        ),
    ]
