# Generated by Django 4.1.2 on 2022-10-25 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bill", "0013_bill_category_type"),
    ]

    operations = [
        migrations.DeleteModel(name="category",),
    ]
