# Generated by Django 4.1.2 on 2022-10-25 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bill", "0014_delete_category"),
    ]

    operations = [
        migrations.RenameField(
            model_name="bill", old_name="category_type", new_name="category_name",
        ),
    ]
