# Generated by Django 4.1.2 on 2022-10-25 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("category_name", models.CharField(max_length=100, unique=True)),
                ("source_type", models.CharField(max_length=100)),
                ("user_id", models.IntegerField(null=True)),
                ("category_icon_name", models.CharField(max_length=100)),
            ],
        ),
    ]
